from datetime import timedelta

from django.test import TestCase
from django.utils import timezone
from rest_framework.test import APIClient

from apps.accounts.models import User
from apps.clients.models import Client
from apps.equipment.models import Equipment
from apps.work_orders.models import WorkOrder


def make_fixtures():
    client = Client.objects.create(
        name="Hospital de Prueba",
        ruc="1790012345010",
        client_type=Client.ClientType.PUBLIC,
        address="Av. Siempre Viva",
        city="Quito",
        province="Pichincha",
        nda_signed=True,
        status=Client.Status.ACTIVE,
    )
    equipment = Equipment.objects.create(
        internal_code="DIM-TEST-001",
        serial_number="SN-TEST-001",
        modality=Equipment.Modality.XRAY_FIXED,
        brand="ACME",
        model_name="X1",
        client=client,
        city="Quito",
        province="Pichincha",
    )
    technician = User.objects.create_user(
        username="tecnico1", password="pw", role=User.Role.TECHNICIAN
    )
    coordinator = User.objects.create_user(
        username="coord1", password="pw", role=User.Role.COORDINATOR
    )
    return client, equipment, technician, coordinator


class WorkOrderModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.client_org, cls.equipment, cls.technician, _ = make_fixtures()

    def _ot(self, **overrides):
        defaults = dict(
            ot_type=WorkOrder.Type.CORRECTIVE,
            equipment=self.equipment,
            client=self.client_org,
            technician=self.technician,
        )
        defaults.update(overrides)
        return WorkOrder.objects.create(**defaults)

    def test_number_is_autogenerated(self):
        ot = self._ot()
        self.assertTrue(ot.number.startswith("OT-"))

    def test_client_autoset_from_equipment(self):
        ot = WorkOrder.objects.create(
            ot_type=WorkOrder.Type.CORRECTIVE,
            equipment=self.equipment,
            technician=self.technician,
        )
        self.assertEqual(ot.client_id, self.client_org.id)

    def test_total_hours_calculated_from_timestamps(self):
        start = timezone.now()
        ot = self._ot(started_at=start, finished_at=start + timedelta(hours=2, minutes=30))
        self.assertEqual(float(ot.total_hours), 2.5)

    def test_cannot_be_closed_until_signed_with_result(self):
        ot = self._ot()
        self.assertFalse(ot.can_be_closed)

    def test_is_signed_by_client_requires_signature_and_timestamp(self):
        ot = self._ot()
        self.assertFalse(ot.is_signed_by_client)


class WorkOrderApiTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.client_org, cls.equipment, cls.technician, cls.coordinator = make_fixtures()

    def setUp(self):
        self.api = APIClient()

    def test_list_requires_authentication(self):
        resp = self.api.get("/api/v1/work-orders/")
        self.assertEqual(resp.status_code, 401)

    def test_lifecycle_open_to_pending_signature(self):
        self.api.force_authenticate(user=self.coordinator)
        resp = self.api.post(
            "/api/v1/work-orders/",
            {
                "ot_type": "CORRECTIVE",
                "equipment": str(self.equipment.id),
                "client": str(self.client_org.id),
                "technician": str(self.technician.id),
                "reported_problem": "Falla intermitente",
            },
            format="json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        ot_id = resp.json()["id"]

        resp = self.api.post(f"/api/v1/work-orders/{ot_id}/start/")
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "IN_PROGRESS")

        resp = self.api.post(f"/api/v1/work-orders/{ot_id}/finish/")
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "PENDING_SIGNATURE")

    def test_evidence_locked_once_signed(self):
        """Checklist/photos/spare parts must be immutable after the client signs."""
        ot = WorkOrder.objects.create(
            ot_type=WorkOrder.Type.CORRECTIVE,
            equipment=self.equipment,
            client=self.client_org,
            technician=self.technician,
            status=WorkOrder.Status.SIGNED,
        )
        self.api.force_authenticate(user=self.coordinator)
        resp = self.api.post(
            f"/api/v1/work-orders/{ot.id}/checklist/",
            {"task_name": "Tarea tardía"},
            format="json",
        )
        self.assertEqual(resp.status_code, 403)
        resp = self.api.post(
            f"/api/v1/work-orders/{ot.id}/spare-parts/",
            {"description": "Repuesto tardío", "quantity": 1, "unit_cost": "10.00"},
            format="json",
        )
        self.assertEqual(resp.status_code, 403)

    def test_evidence_editable_while_in_progress(self):
        ot = WorkOrder.objects.create(
            ot_type=WorkOrder.Type.PREVENTIVE,
            equipment=self.equipment,
            client=self.client_org,
            technician=self.technician,
            status=WorkOrder.Status.IN_PROGRESS,
        )
        self.api.force_authenticate(user=self.technician)
        resp = self.api.post(
            f"/api/v1/work-orders/{ot.id}/checklist/",
            {"task_name": "Verificar frenos", "completed": True},
            format="json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        resp = self.api.post(
            f"/api/v1/work-orders/{ot.id}/spare-parts/",
            {"description": "Filtro de aire", "code": "FA-01", "quantity": 2, "unit_cost": "15.50"},
            format="json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        self.assertEqual(ot.spare_parts_used.count(), 1)
        self.assertEqual(ot.checklist_items.count(), 1)

    def test_technician_only_sees_own_work_orders(self):
        mine = WorkOrder.objects.create(
            ot_type=WorkOrder.Type.CORRECTIVE,
            equipment=self.equipment,
            client=self.client_org,
            technician=self.technician,
        )
        other_tech = User.objects.create_user(
            username="tecnico2", password="pw", role=User.Role.TECHNICIAN
        )
        WorkOrder.objects.create(
            ot_type=WorkOrder.Type.CORRECTIVE,
            equipment=self.equipment,
            client=self.client_org,
            technician=other_tech,
        )
        self.api.force_authenticate(user=self.technician)
        resp = self.api.get("/api/v1/work-orders/")
        self.assertEqual(resp.status_code, 200)
        ids = [row["id"] for row in resp.json()["results"]]
        self.assertEqual(ids, [str(mine.id)])
