# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('equipment', '0001_initial'),
        ('spare_parts', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de OT')),
                ('ot_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('CALIBRATION', 'Calibración'), ('INSTALLATION', 'Instalación'), ('WARRANTY', 'Garantía')], max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('URGENT', 'Urgente'), ('NORMAL', 'Normal'), ('SCHEDULED', 'Programado')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En ejecución'), ('PENDING_SIGNATURE', 'Pendiente de firma cliente'), ('SIGNED', 'Firmada por cliente'), ('CLOSED', 'Cerrada y bloqueada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('executing_company', models.CharField(choices=[('VIAT', 'Viat'), ('DIMED', 'Dimed Healthcare')], default='VIAT', max_length=10, verbose_name='Empresa ejecutora')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='Llegada al sitio')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del trabajo')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del trabajo')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total horas')),
                ('reported_problem', models.TextField(blank=True, verbose_name='Problema reportado')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('work_performed', models.TextField(blank=True, verbose_name='Trabajo realizado')),
                ('result', models.CharField(blank=True, choices=[('RESOLVED', 'Resuelto'), ('PARTIAL', 'Parcial'), ('FOLLOW_UP', 'Seguimiento'), ('NOT_RESOLVED', 'No resuelto')], max_length=20, verbose_name='Resultado')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Notas de seguimiento')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos de traslado')),
                ('client_signature', models.ImageField(blank=True, upload_to='work_orders/signatures/', verbose_name='Rúbrica del cliente')),
                ('client_signer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de quien firma')),
                ('client_signer_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo de quien firma')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de firma')),
                ('technician_signature', models.ImageField(blank=True, upload_to='work_orders/signatures/', verbose_name='Firma del técnico')),
                ('technician_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora firma técnico')),
                ('pdf_document', models.FileField(blank=True, upload_to='work_orders/pdfs/', verbose_name='PDF generado')),
                ('signature_email_sent', models.BooleanField(default=False, verbose_name='Email para firma electrónica enviado')),
                ('electronic_signature_document', models.FileField(blank=True, upload_to='work_orders/signed_pdfs/', verbose_name='Documento con firma electrónica')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='clients.client', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='contracts.contract', verbose_name='Contrato vinculado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment', verbose_name='Equipo')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='templates_engine.templateversion', verbose_name='Versión de plantilla')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=500, verbose_name='Tarea')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='Frecuencia')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('measured_value', models.CharField(blank=True, max_length=100, verbose_name='Valor medido')),
                ('reference_value', models.CharField(blank=True, max_length=100, verbose_name='Valor de referencia')),
                ('tolerance', models.CharField(blank=True, max_length=100, verbose_name='Tolerancia')),
                ('is_within_tolerance', models.BooleanField(null=True, verbose_name='Dentro de tolerancia')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('photo', models.ImageField(blank=True, upload_to='work_orders/checklist_photos/', verbose_name='Foto de evidencia')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Ítem de checklist ejecutado',
                'verbose_name_plural': 'Ítems de checklist ejecutados',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='work_orders/photos/', verbose_name='Foto')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Antes'), ('DURING', 'Durante'), ('AFTER', 'Después')], max_length=10, verbose_name='Tipo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Foto de OT',
                'verbose_name_plural': 'Fotos de OT',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo unitario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usage', to='spare_parts.sparepart', verbose_name='Repuesto del inventario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts_used', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Repuesto utilizado',
                'verbose_name_plural': 'Repuestos utilizados',
            },
        ),
    ]
