# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_code', models.CharField(help_text='Formato: DIM-[TIPO]-[NÚMERO]', max_length=30, unique=True, verbose_name='Código interno Dimed')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de serie del fabricante')),
                ('hospital_asset_number', models.CharField(blank=True, max_length=100, verbose_name='Número de activo del hospital')),
                ('arcsa_registration', models.CharField(blank=True, max_length=100, verbose_name='Registro sanitario ARCSA')),
                ('has_fda', models.BooleanField(default=False, verbose_name='Certificación FDA')),
                ('has_ce', models.BooleanField(default=False, verbose_name='Certificación CE')),
                ('has_iso_13485', models.BooleanField(default=False, verbose_name='ISO 13485')),
                ('modality', models.CharField(choices=[('XRAY_FIXED', 'Rayos X Fijo'), ('XRAY_PORTABLE', 'Rayos X Portátil'), ('CT', 'Tomógrafo (TAC)'), ('MRI', 'Resonancia Magnética'), ('ULTRASOUND', 'Ultrasonido'), ('MAMMOGRAPH', 'Mamógrafo'), ('FLUOROSCOPE', 'Fluoroscopio'), ('DENSITOMETER', 'Densitómetro'), ('OTHER', 'Otro')], max_length=20, verbose_name='Modalidad')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='País de origen')),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fabricación')),
                ('technical_specs', models.JSONField(blank=True, default=dict, verbose_name='Especificaciones técnicas')),
                ('area', models.CharField(blank=True, max_length=200, verbose_name='Área/Sala/Piso')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('MAINTENANCE', 'En mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('DECOMMISSIONED', 'Baja')], default='OPERATIONAL', max_length=20, verbose_name='Estado')),
                ('factory_warranty_start', models.DateField(blank=True, null=True, verbose_name='Garantía fábrica inicio')),
                ('factory_warranty_end', models.DateField(blank=True, null=True, verbose_name='Garantía fábrica fin')),
                ('dimed_warranty_start', models.DateField(blank=True, null=True, verbose_name='Garantía Dimed inicio')),
                ('dimed_warranty_end', models.DateField(blank=True, null=True, verbose_name='Garantía Dimed fin')),
                ('photo', models.ImageField(blank=True, upload_to='equipment/photos/', verbose_name='Foto del equipo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='clients.client', verbose_name='Institución cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='contracts.contract', verbose_name='Contrato vinculado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('maintenance_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='templates_engine.maintenancetemplate', verbose_name='Plantilla de mantenimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['internal_code'],
            },
        ),
    ]
