# Generated by Django 5.1.6 on 2026-08-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='internal_code',
            field=models.CharField(blank=True, help_text='Se genera automáticamente: DIM-[TIPO]-[NÚMERO]', max_length=30, unique=True, verbose_name='Código interno Dimed'),
        ),
    ]
