# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('concept', models.CharField(max_length=500, verbose_name='Concepto')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('income_tax_retention', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención de renta')),
                ('iva_retention', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención de IVA')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('document', models.FileField(blank=True, upload_to='billing/invoices/', verbose_name='Documento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_orders', models.ManyToManyField(blank=True, related_name='client_invoices', to='work_orders.workorder', verbose_name='Órdenes de trabajo')),
            ],
            options={
                'verbose_name': 'Factura a Cliente',
                'verbose_name_plural': 'Facturas a Clientes',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='ViatPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viat_invoice_number', models.CharField(max_length=50, verbose_name='Número de factura Viat')),
                ('viat_invoice_date', models.DateField(verbose_name='Fecha de factura Viat')),
                ('viat_invoice_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto factura Viat')),
                ('viat_invoice_document', models.FileField(upload_to='billing/viat_invoices/', verbose_name='Documento factura Viat')),
                ('concept', models.CharField(max_length=500, verbose_name='Concepto')),
                ('agreed_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor acordado')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferencia')),
                ('difference_justification', models.TextField(blank=True, verbose_name='Justificación de diferencia')),
                ('status', models.CharField(choices=[('PENDING_OT', 'Pendiente de OT firmada'), ('OT_SIGNED_WAITING_INVOICE', 'OT firmada, esperando factura'), ('IN_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('PAID', 'Pagado'), ('REJECTED', 'Rechazado')], default='PENDING_OT', max_length=30, verbose_name='Estado')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('payment_proof', models.FileField(blank=True, upload_to='billing/payment_proofs/', verbose_name='Comprobante de pago')),
                ('evidence_photos_verified', models.BooleanField(default=False, verbose_name='Fotos de evidencia verificadas')),
                ('technical_report_received', models.BooleanField(default=False, verbose_name='Informe técnico recibido')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_viat_payments', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_orders', models.ManyToManyField(related_name='viat_payments', to='work_orders.workorder', verbose_name='Órdenes de trabajo')),
            ],
            options={
                'verbose_name': 'Pago a Viat',
                'verbose_name_plural': 'Pagos a Viat',
                'ordering': ['-created_at'],
            },
        ),
    ]
