from datetime import date

from django.core import mail
from django.test import TestCase
from rest_framework.test import APIClient

from apps.accounts.models import User
from apps.clients.models import Client
from apps.contracts.models import Contract
from apps.equipment.models import Equipment
from apps.tickets.models import Ticket, TicketComment
from apps.tickets.tasks import send_ticket_email


def make_fixtures():
    client = Client.objects.create(
        name="Hospital de Prueba",
        ruc="1790012345020",
        client_type=Client.ClientType.PUBLIC,
        address="Av. Siempre Viva",
        city="Quito",
        province="Pichincha",
        nda_signed=True,
        status=Client.Status.ACTIVE,
    )
    contract = Contract.objects.create(
        number="CT-TEST-001",
        contract_type="ALL_INCLUSIVE",
        client=client,
        start_date=date(2026, 1, 1),
        end_date=date(2027, 1, 1),
        total_value="10000.00",
        sla_response_hours=48,
        preventive_visits_per_year=2,
        status="ACTIVE",
    )
    equipment = Equipment.objects.create(
        internal_code="DIM-TEST-010",
        serial_number="SN-TEST-010",
        modality=Equipment.Modality.XRAY_FIXED,
        brand="ACME",
        model_name="X1",
        client=client,
        city="Quito",
        province="Pichincha",
        contract=contract,
    )
    coordinator = User.objects.create_user(
        username="coord-tkt", password="pw", role=User.Role.COORDINATOR,
        email="coord@dimed.test",
    )
    portal_user = User.objects.create_user(
        username="portal-tkt", password="pw", role=User.Role.CLIENT,
        company_type=User.CompanyType.CLIENT, client_organization=client,
    )
    return client, contract, equipment, coordinator, portal_user


class TicketModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        (cls.client_org, cls.contract, cls.equipment,
         cls.coordinator, cls.portal_user) = make_fixtures()

    def test_number_autogenerated(self):
        t = Ticket.objects.create(
            client=self.client_org, subject="Falla X", description="detalle"
        )
        self.assertTrue(t.number.startswith("TKT-"))

    def test_sla_and_contract_derived_from_equipment(self):
        t = Ticket.objects.create(
            client=self.client_org,
            equipment=self.equipment,
            subject="Equipo con error",
            description="detalle",
        )
        self.assertEqual(t.contract_id, self.contract.id)
        self.assertIsNotNone(t.sla_due_at)


class TicketApiTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        (cls.client_org, cls.contract, cls.equipment,
         cls.coordinator, cls.portal_user) = make_fixtures()

    def setUp(self):
        self.api = APIClient()

    def _create_ticket(self, **overrides):
        defaults = dict(
            client=self.client_org, subject="Falla", description="detalle"
        )
        defaults.update(overrides)
        return Ticket.objects.create(**defaults)

    def test_client_portal_sees_only_own_tickets(self):
        mine = self._create_ticket()
        other_client = Client.objects.create(
            name="Otra Clinica", ruc="1790012345021",
            client_type=Client.ClientType.PRIVATE, address="X",
            city="Quito", province="Pichincha",
            nda_signed=True, status=Client.Status.ACTIVE,
        )
        self._create_ticket(client=other_client)

        self.api.force_authenticate(user=self.portal_user)
        resp = self.api.get("/api/v1/tickets/")
        self.assertEqual(resp.status_code, 200)
        ids = [t["id"] for t in resp.json()["results"]]
        self.assertEqual(ids, [str(mine.id)])

    def test_internal_comments_hidden_from_client(self):
        ticket = self._create_ticket()
        TicketComment.objects.create(
            ticket=ticket, body="Nota interna", is_internal=True,
            created_by=self.coordinator,
        )
        TicketComment.objects.create(
            ticket=ticket, body="Respuesta al cliente", is_internal=False,
            created_by=self.coordinator,
        )

        self.api.force_authenticate(user=self.portal_user)
        resp = self.api.get(f"/api/v1/tickets/{ticket.id}/")
        bodies = [c["body"] for c in resp.json()["comments"]]
        self.assertEqual(bodies, ["Respuesta al cliente"])

        self.api.force_authenticate(user=self.coordinator)
        resp = self.api.get(f"/api/v1/tickets/{ticket.id}/")
        self.assertEqual(len(resp.json()["comments"]), 2)

    def test_resolve_and_close_flow(self):
        ticket = self._create_ticket()
        self.api.force_authenticate(user=self.coordinator)

        resp = self.api.post(
            f"/api/v1/tickets/{ticket.id}/resolve/",
            {"resolution_notes": "Se reemplazó el fusible."},
            format="json",
        )
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "RESOLVED")
        self.assertIsNotNone(resp.json()["resolved_at"])

        resp = self.api.post(f"/api/v1/tickets/{ticket.id}/close/")
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "CLOSED")

    def test_client_cannot_write_internal_note(self):
        ticket = self._create_ticket()
        self.api.force_authenticate(user=self.portal_user)
        resp = self.api.post(
            f"/api/v1/tickets/{ticket.id}/comments/",
            {"body": "¿Alguna novedad?", "is_internal": True},
            format="json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        comment = TicketComment.objects.get(pk=resp.json()["id"])
        self.assertFalse(comment.is_internal)


class TicketEmailTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        (cls.client_org, cls.contract, cls.equipment,
         cls.coordinator, cls.portal_user) = make_fixtures()

    def test_send_ticket_email_includes_number_in_subject(self):
        ticket = Ticket.objects.create(
            client=self.client_org,
            subject="Error E-105",
            description="detalle",
            reported_by_email="contacto@hospital.test",
        )
        sent = send_ticket_email(str(ticket.id), "created")
        self.assertTrue(sent)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn(ticket.number, mail.outbox[0].subject)
        self.assertIn("contacto@hospital.test", mail.outbox[0].to)
        self.assertIn("coord@dimed.test", mail.outbox[0].to)

    def test_internal_comment_not_emailed_to_client(self):
        ticket = Ticket.objects.create(
            client=self.client_org,
            subject="Error E-105",
            description="detalle",
            reported_by_email="contacto@hospital.test",
        )
        comment = TicketComment.objects.create(
            ticket=ticket, body="nota interna", is_internal=True,
            created_by=self.coordinator,
        )
        send_ticket_email(str(ticket.id), "comment", comment_id=str(comment.id))
        self.assertEqual(len(mail.outbox), 1)
        self.assertNotIn("contacto@hospital.test", mail.outbox[0].to)
