# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de la plantilla')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('modality', models.CharField(choices=[('XRAY_FIXED', 'Rayos X Fijo'), ('XRAY_PORTABLE', 'Rayos X Portátil'), ('CT', 'Tomógrafo (TAC)'), ('MRI', 'Resonancia Magnética'), ('ULTRASOUND', 'Ultrasonido'), ('MAMMOGRAPH', 'Mamógrafo'), ('FLUOROSCOPE', 'Fluoroscopio'), ('DENSITOMETER', 'Densitómetro'), ('OTHER', 'Otro')], max_length=20, verbose_name='Modalidad')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('template_type', models.CharField(choices=[('CUSTOM', 'Personalizada'), ('GENERAL', 'General')], max_length=10, verbose_name='Tipo de plantilla')),
                ('status', models.CharField(choices=[('GENERATED', 'Generada'), ('PENDING', 'Pendiente'), ('NO_MANUAL', 'Sin manual')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('template_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de la plantilla')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_templates', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Mantenimiento',
                'verbose_name_plural': 'Plantillas de Mantenimiento',
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('modality', models.CharField(choices=[('XRAY_FIXED', 'Rayos X Fijo'), ('XRAY_PORTABLE', 'Rayos X Portátil'), ('CT', 'Tomógrafo (TAC)'), ('MRI', 'Resonancia Magnética'), ('ULTRASOUND', 'Ultrasonido'), ('MAMMOGRAPH', 'Mamógrafo'), ('FLUOROSCOPE', 'Fluoroscopio'), ('DENSITOMETER', 'Densitómetro'), ('OTHER', 'Otro')], max_length=20, verbose_name='Modalidad')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('language', models.CharField(max_length=50, verbose_name='Idioma')),
                ('file', models.FileField(upload_to='manuales/', verbose_name='Archivo del manual')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Técnico',
                'verbose_name_plural': 'Manuales Técnicos',
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('template_data', models.JSONField(default=dict, verbose_name='Datos de la versión')),
                ('change_notes', models.TextField(blank=True, verbose_name='Notas del cambio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='templates_engine.maintenancetemplate', verbose_name='Plantilla')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Plantilla',
                'verbose_name_plural': 'Versiones de Plantilla',
                'ordering': ['-created_at'],
            },
        ),
    ]
