from decimal import Decimal

from django.test import TestCase
from rest_framework.test import APIClient

from apps.accounts.models import User
from apps.clients.models import Client
from apps.equipment.models import Equipment
from apps.quotes.models import Quote, QuoteItem


def make_fixtures():
    client = Client.objects.create(
        name="Clínica Sin Contrato",
        ruc="1790012345050",
        client_type=Client.ClientType.PRIVATE,
        address="Av. X",
        city="Quito",
        province="Pichincha",
        nda_signed=True,
        status=Client.Status.ACTIVE,
    )
    equipment = Equipment.objects.create(
        internal_code="DIM-TEST-050",
        serial_number="SN-TEST-050",
        modality=Equipment.Modality.XRAY_FIXED,
        brand="ACME",
        model_name="X2",
        client=client,
        city="Quito",
        province="Pichincha",
    )
    coordinator = User.objects.create_user(
        username="coord-quote", password="pw", role=User.Role.COORDINATOR
    )
    technician = User.objects.create_user(
        username="tec-quote", password="pw", role=User.Role.TECHNICIAN
    )
    return client, equipment, coordinator, technician


class QuoteModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.client_org, cls.equipment, cls.coordinator, cls.technician = make_fixtures()

    def test_number_and_validity_autogenerated(self):
        q = Quote.objects.create(
            title="Reparación colimador", client=self.client_org
        )
        self.assertTrue(q.number.startswith("COT-"))
        self.assertIsNotNone(q.valid_until)

    def test_totals_and_advance(self):
        q = Quote.objects.create(title="Repuesto X", client=self.client_org)
        QuoteItem.objects.create(
            quote=q, description="Tubo RX", quantity=1, unit_price=Decimal("1000.00")
        )
        QuoteItem.objects.create(
            quote=q, kind="LABOR", description="Instalación",
            quantity=2, unit_price=Decimal("100.00"),
        )
        self.assertEqual(q.subtotal, Decimal("1200.00"))
        self.assertEqual(q.iva_amount, Decimal("180.00"))
        self.assertEqual(q.total, Decimal("1380.00"))
        self.assertEqual(q.advance_amount, Decimal("690.00"))
        self.assertEqual(q.balance_amount, Decimal("690.00"))


class QuoteApiTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.client_org, cls.equipment, cls.coordinator, cls.technician = make_fixtures()

    def setUp(self):
        self.api = APIClient()
        self.api.force_authenticate(user=self.coordinator)

    def _create_quote(self):
        resp = self.api.post(
            "/api/v1/quotes/",
            {
                "title": "Cambio de detector",
                "client": str(self.client_org.id),
                "equipment": str(self.equipment.id),
                "items": [
                    {"kind": "PART", "description": "Detector FPD", "quantity": 1,
                     "unit_price": "5000.00"},
                    {"kind": "LABOR", "description": "Instalación y calibración",
                     "quantity": 1, "unit_price": "800.00"},
                ],
            },
            format="json",
        )
        return resp

    def test_create_with_items(self):
        resp = self._create_quote()
        self.assertEqual(resp.status_code, 201, resp.content)
        body = resp.json()
        self.assertEqual(len(body["items"]), 2)
        self.assertEqual(body["total"], "6670.00")  # 5800 + 15% IVA

    def test_full_lifecycle_to_ot(self):
        quote_id = self._create_quote().json()["id"]

        # Cannot generate OT before acceptance + advance
        resp = self.api.post(f"/api/v1/quotes/{quote_id}/generate_ot/",
                             {"technician": str(self.technician.id)}, format="json")
        self.assertEqual(resp.status_code, 400)

        resp = self.api.post(f"/api/v1/quotes/{quote_id}/send/")
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "SENT")

        resp = self.api.post(
            f"/api/v1/quotes/{quote_id}/accept/",
            {"accepted_by_name": "Dr. Cliente"},
            format="json",
        )
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.json()["status"], "ACCEPTED")

        resp = self.api.post(f"/api/v1/quotes/{quote_id}/mark_advance_paid/")
        self.assertEqual(resp.status_code, 200)
        self.assertTrue(resp.json()["advance_paid"])

        resp = self.api.post(
            f"/api/v1/quotes/{quote_id}/generate_ot/",
            {"technician": str(self.technician.id)},
            format="json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        ot_number = resp.json()["number"]
        self.assertTrue(ot_number.startswith("OT-"))

        quote = Quote.objects.get(pk=quote_id)
        self.assertEqual(quote.work_order.number, ot_number)

    def test_sent_quote_is_frozen(self):
        quote_id = self._create_quote().json()["id"]
        self.api.post(f"/api/v1/quotes/{quote_id}/send/")
        resp = self.api.patch(
            f"/api/v1/quotes/{quote_id}/", {"title": "Otro"}, format="json"
        )
        self.assertEqual(resp.status_code, 400)

    def test_client_portal_sees_only_non_draft_own_quotes(self):
        quote_id = self._create_quote().json()["id"]
        portal = User.objects.create_user(
            username="portal-quote", password="pw", role=User.Role.CLIENT,
            company_type=User.CompanyType.CLIENT, client_organization=self.client_org,
        )
        self.api.force_authenticate(user=portal)
        resp = self.api.get("/api/v1/quotes/")
        self.assertEqual(resp.json()["count"], 0)  # still DRAFT

        self.api.force_authenticate(user=self.coordinator)
        self.api.post(f"/api/v1/quotes/{quote_id}/send/")
        self.api.force_authenticate(user=portal)
        resp = self.api.get("/api/v1/quotes/")
        self.assertEqual(resp.json()["count"], 1)
