# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINATOR', 'Coordinador'), ('TECHNICIAN', 'Técnico'), ('MANAGEMENT', 'Gerencia'), ('CLIENT', 'Cliente')], default='TECHNICIAN', max_length=20)),
                ('company_type', models.CharField(choices=[('DIMED', 'Dimed Healthcare'), ('VIAT', 'Viat'), ('CLIENT', 'Cliente')], default='DIMED', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA habilitado')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Política de privacidad aceptada')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('EXPORT', 'Exportar'), ('SIGN', 'Firmar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID del objeto')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
