# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de la institución')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('client_type', models.CharField(choices=[('PUBLIC', 'Público'), ('PRIVATE', 'Privado')], max_length=10, verbose_name='Tipo de cliente')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email institucional')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='INACTIVE', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nda_signed', models.BooleanField(default=False, verbose_name='NDA firmado')),
                ('nda_document', models.FileField(blank=True, upload_to='clients/nda/', verbose_name='Documento NDA')),
                ('nda_signed_date', models.DateField(blank=True, null=True, verbose_name='Fecha firma NDA')),
                ('ruc_document', models.FileField(blank=True, upload_to='clients/ruc/', verbose_name='Documento RUC')),
                ('contract_document', models.FileField(blank=True, upload_to='clients/contracts/', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email institucional')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('is_signer', models.BooleanField(default=False, verbose_name='Autorizado para firmar OT')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
