# Generated by Django 5.1.6 on 2026-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_representative_role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo del representante'),
        ),
    ]
