# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('equipment', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('BIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], max_length=10, verbose_name='Frecuencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerta enviada')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenances', to='contracts.contract', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenances', to='equipment.equipment', verbose_name='Equipo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenances', to='work_orders.workorder', verbose_name='Orden de trabajo')),
            ],
            options={
                'verbose_name': 'Mantenimiento Programado',
                'verbose_name_plural': 'Mantenimientos Programados',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
