# Generated by Django 5.1.6 on 2026-03-17 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('contract_type', models.CharField(choices=[('ALL_INCLUSIVE', 'Todo incluido'), ('PREVENTIVE_ONLY', 'Solo preventivo'), ('FACTORY_WARRANTY', 'Garantía de fábrica'), ('TECHNICAL_WARRANTY', 'Garantía técnica'), ('PER_EVENT', 'Por evento')], max_length=20, verbose_name='Tipo de contrato')),
                ('sercop_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia SERCOP')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('payment_terms', models.TextField(verbose_name='Condiciones de pago')),
                ('sla_response_hours', models.PositiveIntegerField(verbose_name='Horas de respuesta SLA')),
                ('preventive_visits_per_year', models.PositiveIntegerField(verbose_name='Visitas preventivas por año')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('document', models.FileField(blank=True, upload_to='contracts/', verbose_name='Documento del contrato')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date'],
            },
        ),
    ]
